"""empty message

Revision ID: 39bbdaab2bdb
Revises: 
Create Date: 2018-07-23 12:55:07.143478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bbdaab2bdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_key', sa.String(length=100), nullable=False),
    sa.Column('product_secret', sa.String(length=100), nullable=True),
    sa.Column('data_format', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.Integer(), nullable=False),
    sa.Column('aliyun_commodity_code', sa.String(length=100), nullable=True),
    sa.Column('gmt_create', sa.DateTime(), nullable=True),
    sa.Column('gmt_update', sa.DateTime(), nullable=True),
    sa.Column('product_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('project_href', sa.String(length=100), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('gmt_create', sa.DateTime(), nullable=True),
    sa.Column('gmt_update', sa.DateTime(), nullable=True),
    sa.Column('project_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iot_id', sa.String(length=100), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_secret', sa.String(length=100), nullable=False),
    sa.Column('gmt_create', sa.DateTime(), nullable=True),
    sa.Column('gmt_active', sa.DateTime(), nullable=True),
    sa.Column('gmt_online', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('firmware_version', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=30), nullable=True),
    sa.Column('node_type', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daq_alarm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('gmt_alarm', sa.DateTime(), nullable=True),
    sa.Column('alarm_value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('gmt_daq', sa.DateTime(), nullable=True),
    sa.Column('daq_value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daqs')
    op.drop_table('daq_alarm')
    op.drop_table('devices')
    op.drop_table('roles_users')
    op.drop_table('projects')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
