"""empty message

Revision ID: 7129f703da4e
Revises: 05c8f56a44de
Create Date: 2018-05-07 16:39:57.728592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7129f703da4e'
down_revision = '05c8f56a44de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daq_power',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('voltage1', sa.Float(), nullable=True),
    sa.Column('current1', sa.Float(), nullable=True),
    sa.Column('voltage2', sa.Float(), nullable=True),
    sa.Column('current2', sa.Float(), nullable=True),
    sa.Column('voltage3', sa.Float(), nullable=True),
    sa.Column('current3', sa.Float(), nullable=True),
    sa.Column('voltage4', sa.Float(), nullable=True),
    sa.Column('current4', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daq_power')
    # ### end Alembic commands ###
