"""empty message

Revision ID: c7ac852351b1
Revises: ef0102dd2b20
Create Date: 2017-12-17 16:43:13.970628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ac852351b1'
down_revision = 'ef0102dd2b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_status', sa.Column('send_alarm_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_status', 'send_alarm_datetime')
    # ### end Alembic commands ###
